
project_id = "pcoyafgsirrznhmdaiji"

[functions.create-checkout]
verify_jwt = false

[functions.payment-success]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.forward-to-n8n]
verify_jwt = false

[functions.test-survey-integration]
verify_jwt = false

[functions.verify-access-code]
verify_jwt = false

[functions.test-n8n-integration]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.analysis-completed]
verify_jwt = false

[auth]
site_url = "https://atlas-assessments.com"
additional_redirect_urls = ["https://atlas-career-chat.lovable.app", "http://localhost:3000"]

[auth.email]
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirm Your Atlas Assessment Account"
content_path = "./supabase/templates/confirmation.html"

# Auth hooks are configured in Supabase dashboard
# [auth.hooks.send_email]
# enabled = true
# uri = "https://pcoyafgsirrznhmdaiji.supabase.co/functions/v1/send-confirmation-email"
# secrets = ["SEND_EMAIL_HOOK_SECRET"]
