
project_id = "pcoyafgsirrznhmdaiji"

[functions.create-checkout]
verify_jwt = false

[functions.payment-success]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.forward-to-relevance]
verify_jwt = false

[functions.test-survey-integration]
verify_jwt = false
