
project_id = "pcoyafgsirrznhmdaiji"

[functions.create-checkout]
verify_jwt = false

[functions.payment-success]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.forward-to-relevance]
verify_jwt = false

[functions.test-survey-integration]
verify_jwt = false

[functions.verify-access-code]
verify_jwt = false

[functions.test-relevance-with-report-id]
verify_jwt = false

[functions.simple-relevance-test]
verify_jwt = false
