// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcoyafgsirrznhmdaiji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb3lhZmdzaXJyem5obWRhaWppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjMyMDQsImV4cCI6MjA2MzIzOTIwNH0.uoZupoVWhURdVYUSrd3LghBSHnmPc3eFzyq7HtzqiJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);